import './style.css'

const chatHistory = document.getElementById('chat-history');
const promptInput = document.getElementById('prompt-input');
const sendBtn = document.getElementById('send-btn');
const previewIframe = document.getElementById('preview-iframe');
const codeBlock = document.getElementById('code-block');
const tabs = document.querySelectorAll('.tab');

// Mock HTML generation for the hackathon UI prototype
const mockGeneratedHTML = `
<!DOCTYPE html>
<html>
<head>
  <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-slate-900 text-white min-h-screen flex items-center justify-center p-8">
  <div class="max-w-md w-full bg-slate-800 rounded-xl shadow-2xl overflow-hidden border border-slate-700">
    <div class="p-8">
      <div class="uppercase tracking-wide text-sm text-orange-500 font-semibold mb-1">Generated by Lumina</div>
      <h2 class="text-2xl leading-tight font-bold mb-4">Your New Component</h2>
      <p class="text-slate-400 mb-6">This is a live preview of the code generated by the AI model. It uses Tailwind CSS for rapid styling.</p>
      <button class="w-full bg-gradient-to-r from-orange-500 to-orange-400 text-white font-bold py-3 px-4 rounded-lg shadow-lg shadow-orange-500/30 hover:scale-[1.02] transition-transform">
        Get Started
      </button>
    </div>
  </div>
</body>
</html>
`;

function addMessage(text, isUser = false) {
  const msgDiv = document.createElement('div');
  msgDiv.className = `message ${isUser ? 'user-message' : 'ai-message'}`;
  
  const avatarContent = isUser ? '<i class="fi fi-rr-user"></i>' : '<i class="fi fi-rr-magic-wand"></i>';
  
  msgDiv.innerHTML = `
    <div class="avatar">${avatarContent}</div>
    <div class="message-content">${text}</div>
  `;
  
  chatHistory.appendChild(msgDiv);
  chatHistory.scrollTop = chatHistory.scrollHeight;
}

function updatePreview(code) {
  // Update iframe
  const iframeDoc = previewIframe.contentDocument || previewIframe.contentWindow.document;
  iframeDoc.open();
  iframeDoc.write(code);
  iframeDoc.close();
  
  // Update code view
  codeBlock.textContent = code;
}

sendBtn.addEventListener('click', () => {
  const text = promptInput.value.trim();
  if (!text) return;
  
  // Add user message
  addMessage(text, true);
  promptInput.value = '';
  
  // Simulate AI generation delay
  setTimeout(() => {
    addMessage("I've generated the UI based on your request using Tailwind CSS. Here is the live preview:");
    updatePreview(mockGeneratedHTML);
  }, 1000);
});

// Tab Switching
tabs.forEach(tab => {
  tab.addEventListener('click', () => {
    tabs.forEach(t => t.classList.remove('active'));
    tab.classList.add('active');
    
    const target = tab.dataset.target;
    if (target === 'preview') {
      previewIframe.classList.remove('hidden');
      document.getElementById('code-view').classList.add('hidden');
    } else {
      previewIframe.classList.add('hidden');
      document.getElementById('code-view').classList.remove('hidden');
    }
  });
});

// Button Actions & Modals
// Button Actions & Modals
const btnSettings = document.getElementById('btn-settings');
const btnDeploy = document.getElementById('btn-deploy');
const btnRefresh = document.getElementById('btn-refresh');
const btnExpand = document.getElementById('btn-expand');
const modalOverlay = document.getElementById('modal-overlay');
const btnCloseModal = document.getElementById('btn-close-modal');
const btnSaveSettings = document.getElementById('btn-save-settings');
const toast = document.getElementById('toast');
const toastMessage = document.getElementById('toast-message');
const workspace = document.querySelector('.workspace');

// Settings Inputs
const apiKeyInput = document.querySelector('.modal-input[type="password"]');
const systemPromptInput = document.querySelector('.modal-input[placeholder="You are an expert UI developer..."]');

// Load settings from LocalStorage
window.addEventListener('DOMContentLoaded', () => {
  const savedKey = localStorage.getItem('fireworks_api_key');
  const savedPrompt = localStorage.getItem('system_prompt');
  if (savedKey) apiKeyInput.value = savedKey;
  if (savedPrompt) systemPromptInput.value = savedPrompt;
  else systemPromptInput.value = "You are an expert UI developer. Create a beautiful, modern, dark-mode Tailwind CSS component based on the user's request. Output ONLY valid HTML with Tailwind classes inside the <body> tag. Do not use markdown blocks like ```html. Just return the raw HTML.";
});

function showToast(msg) {
  toastMessage.textContent = msg;
  toast.classList.remove('hidden');
  setTimeout(() => toast.classList.add('hidden'), 3000);
}

// Settings Modal
btnSettings.addEventListener('click', () => modalOverlay.classList.remove('hidden'));
btnCloseModal.addEventListener('click', () => modalOverlay.classList.add('hidden'));
btnSaveSettings.addEventListener('click', () => {
  localStorage.setItem('fireworks_api_key', apiKeyInput.value.trim());
  localStorage.setItem('system_prompt', systemPromptInput.value.trim());
  modalOverlay.classList.add('hidden');
  showToast('Settings saved successfully.');
});

// Deploy Action
btnDeploy.addEventListener('click', () => {
  showToast('Deploying application to Edge...');
  setTimeout(() => showToast('Deployed successfully! Link copied to clipboard.'), 2000);
});

// Refresh Action
btnRefresh.addEventListener('click', () => {
  const currentCode = codeBlock.textContent;
  updatePreview(currentCode);
  showToast('Preview refreshed.');
});

// Expand Action
let isExpanded = false;
btnExpand.addEventListener('click', () => {
  isExpanded = !isExpanded;
  if (isExpanded) {
    workspace.classList.add('preview-expanded');
    btnExpand.innerHTML = '<i class="fi fi-rr-compress"></i>';
  } else {
    workspace.classList.remove('preview-expanded');
    btnExpand.innerHTML = '<i class="fi fi-rr-expand"></i>';
  }
});

// Real Fireworks API Generation via Streaming
async function generateFromFireworks(promptText) {
  const apiKey = localStorage.getItem('fireworks_api_key');
  const systemPrompt = localStorage.getItem('system_prompt');
  const selectedModel = document.getElementById('model-select').value;
  const metricsUI = document.getElementById('amd-metrics');
  
  if (!apiKey) {
    showToast('No API Key found. Using mock preview.');
    return null;
  }

  showToast(`Starting inference on ${selectedModel.split('/').pop()}...`);
  metricsUI.classList.add('active');
  metricsUI.innerHTML = `<i class="fi fi-rr-dashboard"></i> AMD GPU: Initializing...`;
  
  try {
    const response = await fetch('https://api.fireworks.ai/inference/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${apiKey}`
      },
      body: JSON.stringify({
        model: selectedModel,
        stream: true,
        messages: [
          { role: 'system', content: systemPrompt },
          { role: 'user', content: promptText }
        ],
        temperature: 0.5,
        max_tokens: 4000
      })
    });

    if (!response.ok) throw new Error(`API Error: ${response.status}`);
    
    const reader = response.body.getReader();
    const decoder = new TextDecoder();
    let fullCode = "";
    let startTime = performance.now();
    let firstTokenTime = null;
    let tokenCount = 0;

    while (true) {
      const { value, done } = await reader.read();
      if (done) break;
      
      if (!firstTokenTime) firstTokenTime = performance.now() - startTime;
      
      const chunk = decoder.decode(value, { stream: true });
      const lines = chunk.split('\n');
      
      for (const line of lines) {
        if (line.startsWith('data: ') && !line.includes('[DONE]')) {
          try {
            const data = JSON.parse(line.slice(6));
            const token = data.choices[0].delta.content || '';
            fullCode += token;
            tokenCount++;
            
            // Update Speedometer UI
            const elapsed = (performance.now() - startTime) / 1000;
            const speed = Math.round(tokenCount / elapsed);
            metricsUI.innerHTML = `<i class="fi fi-rr-dashboard"></i> AMD GPU: ${speed} t/s | TTFT: ${Math.round(firstTokenTime)}ms`;
            
          } catch (e) {}
        }
      }
    }
    
    metricsUI.classList.remove('active');
    return fullCode;
  } catch (error) {
    console.error(error);
    showToast('Failed to generate code from API.');
    metricsUI.classList.remove('active');
    metricsUI.innerHTML = `<i class="fi fi-rr-dashboard"></i> AMD GPU: Error`;
    return null;
  }
}

sendBtn.addEventListener('click', async () => {
  const text = promptInput.value.trim();
  if (!text) return;
  
  // Add user message
  addMessage(text, true);
  promptInput.value = '';
  
  // Try real API first
  const generatedCode = await generateFromFireworks(text);
  
  if (generatedCode) {
    // If we got a real response, extract just the HTML and render
    addMessage("Here is your requested UI, powered by Fireworks AI and Llama 3!");
    updatePreview(`
<!DOCTYPE html>
<html>
<head>
  <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-slate-900 min-h-screen flex items-center justify-center p-8">
  ${generatedCode.replace(/```html|```/g, '')}
</body>
</html>`);
  } else {
    // Fallback to mock generation if no API key
    setTimeout(() => {
      addMessage("I've generated the UI based on your request using Tailwind CSS. Here is the live preview:");
      updatePreview(mockGeneratedHTML);
    }, 1000);
  }
});

// Enter key to send prompt
promptInput.addEventListener('keydown', (e) => {
  if (e.key === 'Enter' && !e.shiftKey) {
    e.preventDefault();
    sendBtn.click();
  }
});

// Initial empty state for preview
updatePreview('<div style="display:flex;height:100vh;align-items:center;justify-content:center;font-family:sans-serif;color:#888;">Preview Area</div>');
